name: sertifikasi_jmp_kp3
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.0
  geocoding: ^2.0.0
  shared_preferences: ^2.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.15.3
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.5
  badges: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
