// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNep6XwuyoMFlHm0aTvX54YWto3aua2k0',
    appId: '1:528285075015:web:e6125d4ca7c41b0357d362',
    messagingSenderId: '528285075015',
    projectId: 'roti-e0b01',
    authDomain: 'roti-e0b01.firebaseapp.com',
    storageBucket: 'roti-e0b01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmE4nbi7OsqaeN9pd50rc18rZ5DkzJew',
    appId: '1:528285075015:android:a98b9a9c88f675f757d362',
    messagingSenderId: '528285075015',
    projectId: 'roti-e0b01',
    storageBucket: 'roti-e0b01.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNep6XwuyoMFlHm0aTvX54YWto3aua2k0',
    appId: '1:528285075015:web:cdeab7bd0599741857d362',
    messagingSenderId: '528285075015',
    projectId: 'roti-e0b01',
    authDomain: 'roti-e0b01.firebaseapp.com',
    storageBucket: 'roti-e0b01.appspot.com',
  );

}